project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
files:
  - source: /SlimSocial_for_Facebook/assets/lang/en-US.json
    translation: /SlimSocial_for_Facebook/assets/lang/%locale%.json
    type: json
    update_option: update_as_unapproved
    languages_mapping:
      locale:
        ar: ar-AR
        bn: bn-IN
        ha: ha-NG
        'no': no-NO
        nb: no-NO
        sr: sr-SP
        ur: ur-PK
