org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true

# Disable 16KB page size compatibility check
# TODO: Remove this when all native libraries support 16KB pages
android.experimental.ndk.checkCompat16kbPageSize=false
